services:
  rtmp:
    image: alfg/nginx-rtmp:latest
    container_name: rtmp-hls
    entrypoint: ["nginx"]
    command: ["-g", "daemon off;", "-c", "/etc/nginx/custom.conf"]
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/custom.conf:ro
      - ./www:/var/www
    restart: unless-stopped
